services:
  games:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6397:6397"
